[dev]
  command = "nodemon app.js"
  port = 5000
  targetPort = 3000
  
  #publish = "dist" 
  #jwtRolePath = "app_metadata.authorization.roles"
  #jwtSecret = "MY_JWT_SECRET_VALUE"
  #autoLaunch = true
  #framework = "#custom"
  #[dev.https]
  #  certFile = "cert.pem"
  #  keyFile = "key.pem"
